### ISSUE TITLE
Preview json files

### ISSUE THREAD

**Issue by akarnokd** [AlexxEG/BSA_Browser#10]
Hi. Fallout 76 uses json files for its curve tables. Could you update the preview feature to show these files as text?

**Comment by AlexxEG** [comment]
I totally missed this, my bad!

Good idea, I'm gonna work on this and see how it goes. Thanks!

EDIT: Think my GitHub notifications isn't working properly, missed your PR too. I was thinking about an integrated text viewer with syntax highlighting, but I'm gonna merge your PR first and work on my thing too. Thanks!
