### ISSUE TITLE
BSA Browser doesn't accept "*.BA2" (upper case) files via drag and drop

### ISSUE THREAD

**Issue by redpizza** [AlexxEG/BSA_Browser#12]
BSA Browser doesn't accept ".BA2"(upper case file extention) files via drag and drop.

It will only accepts ".ba2"(lower case file extention) files via drag and drop.
I tested also ".Ba2" and ".bA2", but BSA Browser denied it.

I've tested with BSA Browser 1.9.9.

**Comment by AlexxEG** [comment]
Whoops, thanks for reporting!
