### ISSUE TITLE
The option window size is small

### ISSUE THREAD

**Issue by tktk11** [AlexxEG/BSA_Browser#13]
The option window size is small, making it difficult to press the OK and Cancel buttons. Even if I maximize it, only the button is sticking out.

Image is here.
https://1drv.ms/u/s!AvZZrjSfqkOcjFprFt3TVsQvMGYb?e=v2UsVx

Quick Extract Path is also.
https://1drv.ms/u/s!AvZZrjSfqkOcjFsDlDDDfCG8rb45?e=24zZ8d

My environment is Windows 10 64bit in Japanese.

**Comment by AlexxEG** [comment]
I've totally missed this issue, I'm sorry. Never got notified.

Looks like it's doing some weird resizing, not sure why. I'll look into it.

**Comment by AlexxEG** [comment]
I believe this is now fixed in since 7692b8d56b720457b84eb79878ffc75c9838849f
