### ISSUE TITLE
Request: Option to prevent overwriting existing files

### ISSUE THREAD

**Issue by Wynadorn** [AlexxEG/BSA_Browser#14]
I'd be nice to have a (CLI) option to prevent overwriting existing files, this because the engine prioritizes loose files over BSA files.

A usage example would be a mod packed as BSA with a couple loose files added as optional hotfix, unpacking would replace the hotfix.

**Comment by Wynadorn** [comment]
Maybe overwriting should be the additional parameter instead of the other way around. (-O)

**Comment by Wynadorn** [comment]
Send a pull request implementing this change, sorry there's also some other changes on that branch, feel free to revert of course

**Comment by AlexxEG** [comment]
Hey, sorry for late reply, my notifications doesn't work properly.

Good idea, I will implement it, but not sure if I want it to be handled in the library. I would prefer it to be handled in the GUI/CLI part of the project.

Thanks for the work!

**Comment by AlexxEG** [comment]
Resolved in #17
