### ISSUE TITLE
inconsistently accessible files

### ISSUE THREAD

**Issue by yarrmateys** [AlexxEG/BSA_Browser#16]
https://www.nexusmods.com/fallout4/mods/43287 this mod has an example of this problem.  sometimes the files aren't properly accessible. in this case, go to meshes/pipboy and look at the files available. there are 3 under CharacterAssets subfolder, Pipboy.nif, PipboyDusty.nif and PipboyLowPlayer.nif. but if you click on the CharacterAssets subfolder, instead of seeing these 3 you'll see a fourth file, Pipbone.nif. it's like there are two or more different folders there and their contents aren't properly combined.

**Comment by AlexxEG** [comment]
Hey, sorry for late reply, my notifications doesn't work properly. I've looked at the issue and it has been fixed in a2aebbdc47af832889ad4bddc6e60b5b786edd1b

Thanks for reporting!
